### PR TITLE
Fixed project path issue on linux

### LINKED ISSUE #21: unexpected folder structure - at: value
Current folder structure:
```diff
|--[csharp]
   |--csharp.sln
   |--[KombiN]
      |--KombiN.csproj
   |--[KombiN.Tests]
      |--KombiN.Tests.csproj
```
compare the "at:" value for below commands
```diff
[user@ws csharp]$ renameproject KombiN kombin
Please review the following settings:
Project:                   KombiN
found at:                  /home/user/libs/KombiN/csharp/KombiN\KombiN.csproj
Rename to:                 kombin
at:                        /home/user/libs/KombiN/kombin/kombin.csproj)
VS Solution folder:        none
exclude:                   
Paket in use:              no
Run paket install:         yes
Run build after rename:    no
Create automatic commit:   yes
Git version:               git version 2.29.2
```
```diff
[user@ws csharp]$ renameproject KombiN ./kombin
Please review the following settings:
Project:                   KombiN
found at:                  /home/user/libs/KombiN/csharp/KombiN\KombiN.csproj
Rename to:                 kombin
at:                        /home/user/libs/KombiN/csharp/kombin/kombin.csproj)
VS Solution folder:        none
exclude:                   
Paket in use:              no
Run paket install:         yes
Run build after rename:    no
Create automatic commit:   yes
Git version:               git version 2.29.2
```
my expectation here was that regardless of the folder structure, it will rename it were old one was found.

### LINKED ISSUE #22: Error: Could not find project or directory because of wrong file path construction
```diff
[user@ws csharp]$ renameproject KombiN ./kombin
Please review the following settings:
Project:                   KombiN
found at:                  /home/user/libs/KombiN/csharp/KombiN\KombiN.csproj
Rename to:                 kombin
at:                        /home/user/libs/KombiN/csharp/kombin/kombin.csproj)
VS Solution folder:        none
exclude:                   
Paket in use:              no
Run paket install:         yes
Run build after rename:    no
Create automatic commit:   yes
Git version:               git version 2.29.2

-----------------------------------------------
Do you want to continue with the rename operation? [Enter=Yes, any other key=No]
Analyzing references in your projects - depending on the number of projects this can take a bit...
Could not find project or directory `/home/user/libs/KombiN/csharp/KombiN\KombiN.csproj`.
call 'dotnet list "/home/user/libs/KombiN/csharp/KombiN\KombiN.csproj" reference' failed - aborting
...running git reset to undo any changes...
HEAD is now at a8e168e changed xml doc and rename test file
```
```diff
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     fedora
 OS Version:  33
 OS Platform: Linux
 RID:         fedora.33-x64
 Base Path:   /usr/lib64/dotnet/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.111 [/usr/lib64/dotnet/sdk]
  5.0.102 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

```

### PR DESCRIPTION
**Pull request by pranav-ninja**
Fixed #21 and Fixed #22 

As absolute path was containing invalid platform specific relative path and it's originally came from MSBuild object [ProjectInSolution.AbsolutePath].

### CODE REVIEW

**Review by ModernRonin — COMMENTED** [review]
looks good. just to be safe, I'll run a few basic manual tests tomorrow, then I'll approve the merge and create a release from your fix - thanks!

**Comment by pranav-ninja** [comment]
I have learned many things fixing this issues and grateful for that. Thank you so much that I was able to contribute.

**Comment by pranav-ninja** [comment]
just kept changes specific to issue.

**Comment by ModernRonin** [comment]
hmm, locally when I add your changes and run the test profiles that are checking into the solution, I hit issues.
I invited you to the repo I use as testbed. Can you check it out locally, into `C:\Projects\Github\ProjectRenamerTestBed`, and then from within VS use the launch config "renamed library to project, in subfolder, no commit, no paket"? Or, you are using VS Code, you maybe have to do this differently, the launch profiles can be found under 'Properties/launchsettings.json'.

If you can't, it's fine, then I'll do it, but that may take a few days because it seems I hurt my shoulder, I need to go and see the doctor.

**Comment by pranav-ninja** [comment]
no worries, will give it a try.

**Comment by ModernRonin** [comment]
so how is it going? do you need assistance? This weekend I hope to be able to spend some time on this...

**Comment by pranav-ninja** [comment]
Hey @ModernRonin 
there is no progress from my side currently. FIX suggested by me is also breaking on Linux few more things along the way. So got setup on Windows and Linux to make it happen. Things work correctly if project is not referenced or referencing other project.
If you got time sure go ahead but I will also make efforts to fix it.

**Comment by ModernRonin** [comment]
Did you get the manual test-scenarios from the other repo to work? I've found they are quite helpful.

**Comment by pranav-ninja** [comment]
I have tried all scenarios and not all are passing specially referenced by and referencing to.
yes other repo was useful and got copy of it so will be using to do manual tests.

**Comment by pranav-ninja** [comment]
All tests in windows are OK on linux side having minor issues will fix and test on both platforms to make sure it works.

**Comment by ModernRonin** [comment]
very cool, pranav and thank you for sticking with this!

**Comment by pranav-ninja** [comment]
Hey @ModernRonin , finally able to finish it. have tested on windows and Linux, with 100% successful tests. Test bed project is awesome and really helpful.

**Comment by ModernRonin** [comment]
I will get to look at this only on the weekend, sorry. But thanks a lot!

**Review by ModernRonin — APPROVED** [review]
merged - I'll update release notes etc and push out the new release - great work, @pranav-ninja , thank you very much!

**Pull request merged**
