### PR TITLE
Update Git.cs

### PR DESCRIPTION
**Pull request by jakubmaguza**
Add quotation marks to avoid error on changing names when path contains space character.

### CODE REVIEW

**Review by ModernRonin — COMMENTED** [review]
Have you tested running the tool locally? 
Because when I apply your change and run the tool against a test-repo I got for these purposes, I get an error. 

I have invited you to the test repo. if you clone it locally to c:\Projects\github\ProjectRenamerTestBed and then use the run config (the launchsettings are checking in in the main repo) called `move and rename root library to subfolder, no paket`, you will see the error happening. (Just put a breakpoint in `Runtime.Abort()`.) 

But in short, it looks like:
```
fatal: bad source, source='C:/Projects/Github/ProjectRenamerTestBed/subfolder/LibraryInSubfolder', destination='C:/Projects/Github/ProjectRenamerTestBed/subfolder/ProjectInSubFolder'
``` 
and a short experiment shows that the exact same error happens if you run git from the command-line - while if you run it from powershell it works.

**Comment by ModernRonin** [comment]
so I guess it's got to do with the single quotes, but maybe you are running on linux or some other *nix and there they work?

and, besides all that, thanks for taking the time to do a PR :-)

**Comment by jakubmaguza** [comment]
Hello!
Yes, I did test it locally, but as you pointed it out, it's working on PowerShell, but don't work on cmd.
I didn't check there, my apologize.

If I remember correctly, double quotes will work on both PowerShell and cmd.
I did my local test again and seems to me it's working fine.

**Comment by ModernRonin** [comment]
either tonight or tomorrow after work I'll run all the test scenarios for the testbed repo (unfortunately, automating these is not easy, so I run them manually which is a bit time-consuming) and if all works as expected,I'll merge your PR and create a new release. thank you!

**Comment by jakubmaguza** [comment]
Thank you for your amazing project!

**Review by ModernRonin — APPROVED** [review]

**Comment by ModernRonin** [comment]
@jakubmaguza new version is available on nuget - thanks once more for your PR!

**Pull request merged**
